@startuml DiagramaClasesDominio
skinparam style strictuml
skinparam linetype ortho


' --- CLASES DE ANALISIS ---
class PantPagoCuota {
  - opPagoCuota
  - prestamosActivos: List
  - prestamoSeleccionado: Prestamo
  - cuotas: List
  - cuotaSeleccionada: Cuota
  - montoBaseCuota: Float

  + opPagoCuota()
  + habilitarVentana()
  + mostrarPrestamosActivos()
  + solicitarSeleccionPrestamo()
  + tomarSeleccionPrestamo()
  + mostrarCuotas()
  + solicitarSeleccionCuotas()
  + tomarSeleccionCuotas()
  + mostrarMontoBase()
  + solicitarConfirmacionPago()
  + tomarConfirmacionPago()
  + mostrarPagoExitoso()
}

class GestorPagoCuota {
  - clienteLogueado : Usuario
  - prestamosActivos : List
  - prestamoSeleccionado : Prestamo
  - cuotasPrestamo : List
  - cuotaSeleccionada : Cuota
  - estadoCuota : String
  - saldoPrestamo : Float
  - estadoPrestamo : String

  + opPagoCuota()
  + buscarClienteLogueado()
  + buscarPrestamosActivos()
  + tomarSeleccionPrestamo()
  + buscarCuotasPrestamo()
  + ordenarCuotasAsc()  
  + tomarSeleccionCuota()
  + buscarEstadoCuota()
  + llamarCUPagoCuota()
  + buscarEstadoParaAsignar()
  + obtenerFechaHoraActual()
  + tomarConfirmacionPago()
  + actualizarEstadoCuota()
  + actualizarSaldoPrestamo()
  + validarEstadoPrestamo()
  + actualizarEstadoPrestamo()
  + finCU()
}

' --- ENTIDADES ---
class Cliente {
  - nombre: String
  - apellido: String
  - nroDocumento: String
  - correoElectronico: Varchar
  - nroTelefono: String
}

class Sesion {
  usuarioLogueado: Usuario

  + obtenerClienteLogueado()
}

class Usuario {
  + nombreUsuario : Varchar
  + clave : Varchar

  + obtenerClienteLogueado()
  + obtenerPrestamosActivos()
}

class Prestamo {
  - numeroPrestamo: int
  - saldoPendiente : Float
  - cantidadCuotas : int
  - cuotasPrestamo : List

  + obtenerPrestamo()
  + obtenerNumero()
  + obtenerSaldoPendiente()
  + obtenerCantidadCuotas()
  + obtenerCuotasPrestamo()
}

class CambioEstadoPrestamo {
  - nombre
  - descripcion
  - fechaHoraInicio
  - fechaHoraFin

  + sosActual()
  + sosActivo()
  + setFechaHoraFin()
}

class EstadoPrestamo {
  - nombre
  - descripcion

  + sosActivo()
  + sosFinalizado()
}

class Cuota {
  - nroCuota : int
  - fechaVencimiento : date
  - montoBase: float

  + obtenerNroCuota()
  + obtenerFechaVto()
  + obtenerMontoBase()
  + obtenerEstadoCuota()
  + crearCambioEstado()
  + actualizarEstadoCuota()
  + obtenerCuotasPendientes()
}


class CambioEstadoCuota {
  - nombre
  - descripcion
  - fechaHoraInicio
  - fechaHoraFin

  + sosActual()
  + sosProgramada()
  + sosPendiente()
  + obtenerEstadoActual()
  + setFechaHoraFin()
}

class EstadoCuota {
  - nombre
  - descripcion
  
  + sosPagada()
}


' --- RELACIONES ---
PantPagoCuota <..> GestorPagoCuota
GestorPagoCuota  ..> "1" Sesion
GestorPagoCuota  ..> "0...*" Prestamo : Prestamo
GestorPagoCuota  ..> "0...*" Cuota : Cuota

Sesion "1" --> "1" Usuario : Usuario
Usuario "1" -> "1" Cliente : Cliente
Cliente "1" --> "0...*" Prestamo : Prestamo

Prestamo "1...*" --> "1" CambioEstadoPrestamo : CambioEstadoPrestamo
CambioEstadoPrestamo "1" -> "1" EstadoPrestamo : EstadoPrestamo

Prestamo "1...*" *-- "1" Cuota : Cuotas
Cuota "1...*" --> "1" CambioEstadoCuota : CambioEstadoCuota
CambioEstadoCuota "1" -> "1" EstadoCuota : EstadoCuota


@enduml


' PREGUNTAS
' Para los atributos, es mejor usar string, o varchar? Nombres, telefono, correo, dni